INSERT INTO
    "service" (
        "id",
        "department",
        "completeCoords",
        "visible",
        "name",
        "address",
        "zipCode",
        "city",
        "phone",
        "email",
        "marianne_text",
        "drac_text",
        "service_text",
        "dept_numbers",
        "courriel_crmh",
        "courriel_caoa",
        "courriel_dreal",
        "courriel_sra",
        "courriel_udap",
        "courriel_ofb"
    )
VALUES (
        'snum',
        '',
        NULL,
        '1',
        'Service du Numérique',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Préfet de la région Île-de-France',
        NULL,
        'Service du Numérique',
        '75',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    );