/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetPasswordLinkRouteImport } from './routes/reset-password.$link'
import { Route as PdfReportIdRouteImport } from './routes/pdf.$reportId'
import { Route as EditReportIdRouteImport } from './routes/edit.$reportId'
import { Route as ConstatConstatIdRouteImport } from './routes/constat.$constatId'
import { Route as ConstatConstatIdPdfRouteImport } from './routes/constat_.$constatId.pdf'

const ResetPasswordIndexLazyRouteImport = createFileRoute('/reset-password/')()

const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordIndexLazyRoute = ResetPasswordIndexLazyRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/reset-password.index.lazy').then((d) => d.Route),
)
const ResetPasswordLinkRoute = ResetPasswordLinkRouteImport.update({
  id: '/reset-password/$link',
  path: '/reset-password/$link',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfReportIdRoute = PdfReportIdRouteImport.update({
  id: '/pdf/$reportId',
  path: '/pdf/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditReportIdRoute = EditReportIdRouteImport.update({
  id: '/edit/$reportId',
  path: '/edit/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstatConstatIdRoute = ConstatConstatIdRouteImport.update({
  id: '/constat/$constatId',
  path: '/constat/$constatId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstatConstatIdPdfRoute = ConstatConstatIdPdfRouteImport.update({
  id: '/constat_/$constatId/pdf',
  path: '/constat/$constatId/pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cgu': typeof CguRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/service': typeof ServiceRoute
  '/constat/$constatId': typeof ConstatConstatIdRoute
  '/edit/$reportId': typeof EditReportIdRoute
  '/pdf/$reportId': typeof PdfReportIdRoute
  '/reset-password/$link': typeof ResetPasswordLinkRoute
  '/reset-password': typeof ResetPasswordIndexLazyRoute
  '/constat/$constatId/pdf': typeof ConstatConstatIdPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cgu': typeof CguRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/service': typeof ServiceRoute
  '/constat/$constatId': typeof ConstatConstatIdRoute
  '/edit/$reportId': typeof EditReportIdRoute
  '/pdf/$reportId': typeof PdfReportIdRoute
  '/reset-password/$link': typeof ResetPasswordLinkRoute
  '/reset-password': typeof ResetPasswordIndexLazyRoute
  '/constat/$constatId/pdf': typeof ConstatConstatIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cgu': typeof CguRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/service': typeof ServiceRoute
  '/constat/$constatId': typeof ConstatConstatIdRoute
  '/edit/$reportId': typeof EditReportIdRoute
  '/pdf/$reportId': typeof PdfReportIdRoute
  '/reset-password/$link': typeof ResetPasswordLinkRoute
  '/reset-password/': typeof ResetPasswordIndexLazyRoute
  '/constat_/$constatId/pdf': typeof ConstatConstatIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cgu'
    | '/connexion'
    | '/inscription'
    | '/mentions-legales'
    | '/service'
    | '/constat/$constatId'
    | '/edit/$reportId'
    | '/pdf/$reportId'
    | '/reset-password/$link'
    | '/reset-password'
    | '/constat/$constatId/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cgu'
    | '/connexion'
    | '/inscription'
    | '/mentions-legales'
    | '/service'
    | '/constat/$constatId'
    | '/edit/$reportId'
    | '/pdf/$reportId'
    | '/reset-password/$link'
    | '/reset-password'
    | '/constat/$constatId/pdf'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cgu'
    | '/connexion'
    | '/inscription'
    | '/mentions-legales'
    | '/service'
    | '/constat/$constatId'
    | '/edit/$reportId'
    | '/pdf/$reportId'
    | '/reset-password/$link'
    | '/reset-password/'
    | '/constat_/$constatId/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CguRoute: typeof CguRoute
  ConnexionRoute: typeof ConnexionRoute
  InscriptionRoute: typeof InscriptionRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  ServiceRoute: typeof ServiceRoute
  ConstatConstatIdRoute: typeof ConstatConstatIdRoute
  EditReportIdRoute: typeof EditReportIdRoute
  PdfReportIdRoute: typeof PdfReportIdRoute
  ResetPasswordLinkRoute: typeof ResetPasswordLinkRoute
  ResetPasswordIndexLazyRoute: typeof ResetPasswordIndexLazyRoute
  ConstatConstatIdPdfRoute: typeof ConstatConstatIdPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$link': {
      id: '/reset-password/$link'
      path: '/reset-password/$link'
      fullPath: '/reset-password/$link'
      preLoaderRoute: typeof ResetPasswordLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf/$reportId': {
      id: '/pdf/$reportId'
      path: '/pdf/$reportId'
      fullPath: '/pdf/$reportId'
      preLoaderRoute: typeof PdfReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$reportId': {
      id: '/edit/$reportId'
      path: '/edit/$reportId'
      fullPath: '/edit/$reportId'
      preLoaderRoute: typeof EditReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constat/$constatId': {
      id: '/constat/$constatId'
      path: '/constat/$constatId'
      fullPath: '/constat/$constatId'
      preLoaderRoute: typeof ConstatConstatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constat_/$constatId/pdf': {
      id: '/constat_/$constatId/pdf'
      path: '/constat/$constatId/pdf'
      fullPath: '/constat/$constatId/pdf'
      preLoaderRoute: typeof ConstatConstatIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CguRoute: CguRoute,
  ConnexionRoute: ConnexionRoute,
  InscriptionRoute: InscriptionRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  ServiceRoute: ServiceRoute,
  ConstatConstatIdRoute: ConstatConstatIdRoute,
  EditReportIdRoute: EditReportIdRoute,
  PdfReportIdRoute: PdfReportIdRoute,
  ResetPasswordLinkRoute: ResetPasswordLinkRoute,
  ResetPasswordIndexLazyRoute: ResetPasswordIndexLazyRoute,
  ConstatConstatIdPdfRoute: ConstatConstatIdPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
