# yaml-language-server: $schema=https://unpkg.com/@powersync/service-sync-rules@latest/schema/sync_rules.json
replication:
  connections:
    - type: postgresql
      uri: !env PS_DATABASE_URL

      # SSL settings
      sslmode: disable # 'verify-full' (default) or 'verify-ca' or 'disable'

# Connection settings for sync bucket storage
storage:
  type: mongodb
  uri: mongodb://mongo:27017/powersync_demo

# The port which the PowerSync API server will listen on
port: !env PS_PORT
sync_config:
  path: sync-config.yaml

# Settings for client authentication
# Tokens are HS256 JWTs issued by the backend, signed with JWT_SECRET
client_auth:
  supabase_jwt_secret: !env PS_JWT_SECRET

  # Settings for telemetry reporting
  # See https://docs.powersync.com/self-hosting/telemetry
  telemetry:
    # Opt out of reporting anonymized usage metrics to PowerSync telemetry service
    disable_telemetry_sharing: false
